version: '3.8'

services:
  catalogservice:
    build: ./CatalogService
    ports:
      - "5001:8080"
    volumes:
      - ./CatalogService/logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  orderservice:
    build: ./OrderService
    ports:
      - "5002:8080"
    volumes:
      - ./OrderService/logs:/app/logs
    healthcheck:
        test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
        interval: 10s
        timeout: 5s
        retries: 3

  paymentservice:
    build: ./PaymentService
    ports:
      - "5003:8080"
    volumes:
      - ./PaymentService/logs:/app/logs
    healthcheck:
        test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
        interval: 10s
        timeout: 5s
        retries: 3
    depends_on:
      - rabbitmq

  apigateway:
    build: ./ApiGateway
    ports:
      - "5000:8080"
    volumes:
      - ./ApiGateway/logs:/app/logs
    depends_on:
      - catalogservice
      - orderservice
      - paymentservice
    healthcheck:
        test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
        interval: 10s
        timeout: 5s
        retries: 3

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: